name: varenya_mobile
description: Varenya Flutter Application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  firebase_auth: ^3.2.0
  json_annotation: ^4.4.0
  firebase_storage: ^10.1.0
  uuid: ^3.0.4
  form_field_validator: ^1.1.0
  image_picker: ^0.8.2
  provider: ^6.0.1
  cloud_firestore: ^3.1.0
  firebase_messaging: ^11.1.0
  firebase_analytics: ^8.3.2
  http: ^0.13.3
  intl: ^0.17.0
  expandable: ^5.0.1
  cached_network_image: ^3.2.0

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
